spring:
  application:
    name: flight-api-gateway
server:
  port: 2000
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
zuul:
  prefix: /rest
  routes:
    flight-control-service:
      path: /c/**
      serviceId: FLIGHT-CONTROL-SERVICE
