spring:
  application:
    name: flight-control-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/flight_control_db'
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate: 'dialect:org.hibernate.dialect.MySQL5InnoDBDialect'
server:
  port: 2002
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'